#!/usr/bin/env python3
"""Reproducible local import of NASA NESC F16_package.zip (no redistribution assumed).
Tables and independent checkData are extracted separately; expected outputs are
never evaluated by OpenFlightSim. Outputs include SI JSON provenance and C++.
"""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request
import zipfile
import xml.etree.ElementTree as ET

URL = 'https://nescacademy.nasa.gov/workshop/FlightSim/2015/models/F16_package.zip'
SHA256 = '20c60f615ae8e87d81c9d98b54fff45a2832840201499cbcfe3f45a60ef3e5b2'
NS = {'d': 'http://daveml.org/2010/DAVEML'}
FT = .3048
LBF = 4.4482216152605
SLUG = LBF / FT

def numbers(text):
    return [float(x) for x in text.replace(',', ' ').split()]

def cpp_list(values):
    return '{' + ','.join(format(x, '.17g') for x in values) + '}'

def import_archive(archive, output):
    if hashlib.sha256(archive).hexdigest() != SHA256:
        raise ValueError('NASA archive hash mismatch; review a new revision explicitly')
    output.mkdir(parents=True, exist_ok=True)
    import io
    z = zipfile.ZipFile(io.BytesIO(archive))
    header = ['// Generated by import_nasa_f16.py; tables and checkData from pinned NASA archive.',
              '#pragma once', '#include "ofs/data_model.hpp"', 'namespace ofs::f16_data {']
    entries, checks = [], {}
    for component in ('aero', 'prop', 'inertia'):
        filename = 'F16_' + component + '.dml'
        raw = z.read('F16_package/F16_S119_source/' + filename)
        (output / filename).write_bytes(raw)  # preserve original references/notices
        root = ET.fromstring(raw)
        revision = root.findtext('d:fileHeader/d:fileVersion', namespaces=NS)
        breakpoints = {b.attrib['bpID']: (numbers(b.findtext('d:bpVals', namespaces=NS)), b.attrib['units'])
                       for b in root.findall('d:breakpointDef', NS)}
        for func in root.findall('d:function', NS):
            table = func.find('d:functionDefn/d:griddedTableDef', NS)
            if table is None:
                ref = func.find('d:functionDefn/d:griddedTableRef', NS)
                table = root.find("d:griddedTableDef[@gtID='"+ref.attrib['gtID']+"']", NS)
            name = func.find('d:dependentVarRef', NS).attrib['varID']
            axes, units = zip(*(breakpoints[b.attrib['bpID']] for b in table.findall('d:breakpointRefs/d:bpRef', NS)))
            converted = [[x * (FT if unit == 'ft' else 0.017453292519943295 if unit == 'deg' else 1)
                          for x in axis] for axis, unit in zip(axes, units)]
            values = numbers(table.findtext('d:dataTable', namespaces=NS))
            if component == 'prop':
                values = [x * LBF for x in values]
            if len(values) != __import__('math').prod(map(len, axes)):
                raise ValueError('Grid shape mismatch: ' + name)
            header.append('inline const GridTable& '+name+'() { static const GridTable t({' +
                          ','.join(cpp_list(a) for a in converted)+'},'+cpp_list(values)+'); return t; }')
            entries.append(dict(parameter=name, values=values, axes=converted,
                                unit='N' if component == 'prop' else '1',
                                source=URL + '#' + filename, revision=revision,
                                provenance='REFERENCE', configuration='NASA NESC F-16 model; MRC 35% MAC',
                                validity_envelope=json.dumps([dict(min=min(a), max=max(a), unit='rad' if u=='deg' else 'm' if u=='ft' else u)
                                                   for a,u in zip(converted,units)]),
                                confidence='Published computational reference, not aircraft flight-test evidence',
                                validation_status='NASA independent staticShot checks',
                                notes='Tensor grid, last axis fastest; no extrapolation; original source preserved locally'))
        shots = []
        for shot in root.findall('d:checkData/d:staticShot', NS):
            def signals(section):
                return {s.findtext('d:signalName', namespaces=NS):dict(
                    value=float(s.findtext('d:signalValue', namespaces=NS)),
                    unit=s.findtext('d:signalUnits', namespaces=NS),
                    tolerance=float(s.findtext('d:tol', default='0', namespaces=NS)))
                        for s in shot.findall('d:'+section+'/d:signal', NS)}
            shots.append(dict(name=shot.attrib['name'],inputs=signals('checkInputs'),
                              outputs=signals('checkOutputs'),source=URL+'#'+filename,
                              tolerance_reason='Unchanged tolerance supplied by NASA DAVE-ML checkData'))
        checks[component]=shots
        for v in root.findall('d:variableDef', NS):
            # Propulsion initialValue fields are mutable inputs/outputs, not
            # reference constants (and share names with the deck functions).
            if component in ('aero','inertia') and 'initialValue' in v.attrib:
                value=float(v.attrib['initialValue']); unit=v.attrib['units']
                factor,si_unit={'slugft2':(SLUG*FT*FT,'kg m2'),'slug':(SLUG,'kg'),
                                'ft':(FT,'m'),'ft2':(FT*FT,'m2'),'pct':(.01,'1'),
                                'nd':(1,'1')}.get(unit,(1,unit))
                header.append('inline constexpr double '+v.attrib['varID']+'='+format(value*factor,'.17g')+';')
                entries.append(dict(parameter=v.attrib['varID'],values=value*factor,unit=si_unit,source=URL+'#'+filename,revision=revision,provenance='REFERENCE',configuration='DML default CG=35% MAC (web overview differs)',validity_envelope='Fixed source reference constants',confidence='Published computational reference constants',validation_status='source transcription',notes=v.findtext('d:description',default='',namespaces=NS).strip()))
    header += ['struct AeroCheck { const char* name; std::array<double,9> inputs; std::array<double,6> outputs, tolerance; };',
               'inline const std::array<AeroCheck,'+str(len(checks['aero']))+'> aero_checks{{']
    ikeys=['trueAirspeed','angleOfAttack','angleOfSideslip','bodyAngularRate_Roll','bodyAngularRate_Pitch','bodyAngularRate_Yaw','elevatorDeflection','aileronDeflection','rudderDeflection']
    okeys=['aeroBodyForceCoefficient_X','aeroBodyForceCoefficient_Y','aeroBodyForceCoefficient_Z','aeroBodyMomentCoefficient_Roll','aeroBodyMomentCoefficient_Pitch','aeroBodyMomentCoefficient_Yaw']
    for c in checks['aero']:
        inputs=[c['inputs'][key]['value']*(FT if n==0 else 0.017453292519943295 if n in (1,2,6,7,8) else 1) for n,key in enumerate(ikeys)]
        header.append('{'+json.dumps(c['name'])+','+cpp_list(inputs)+','+cpp_list([c['outputs'][key]['value'] for key in okeys])+','+cpp_list([c['outputs'][key]['tolerance'] for key in okeys])+'},')
    header += ['}};', 'struct PropCheck { const char* name; std::array<double,3> inputs; double output, tolerance; };',
               'inline const std::array<PropCheck,'+str(len(checks['prop']))+'> prop_checks{{']
    for c in checks['prop']:
        inp=c['inputs'];out=c['outputs']['thrustBodyForce_X']
        inputs=[inp['altitudeMSL']['value']*FT,inp['mach']['value'],inp['powerLeverAngle']['value']/100]
        header.append('{'+json.dumps(c['name'])+','+cpp_list(inputs)+','+format(out['value']*LBF,'.17g')+','+format(out['tolerance']*LBF,'.17g')+'},')
    header+=['}};','}']
    (output/'f16_imported.hpp').write_text('\n'.join(header)+'\n')
    (output/'dataset.json').write_text(json.dumps(dict(schema_version=1,aircraft='NASA NESC F-16 reference',configuration='Clean airborne reference; DML default CG=35% MAC',archive_sha256=SHA256,parameters=entries,checks=checks),indent=2)+'\n')
    files = ['F16_aero.dml','F16_prop.dml','F16_inertia.dml','f16_imported.hpp','dataset.json']
    (output/'import-integrity.json').write_text(json.dumps({f:hashlib.sha256((output/f).read_bytes()).hexdigest() for f in files},indent=2)+'\n')
    print(f'Imported {len(entries)} parameters/tables, {len(checks["aero"])} aero and {len(checks["prop"])} propulsion independent checks into {output}')

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--archive',type=Path,help='Use a local archive instead of downloading NASA source')
    p.add_argument('--output',type=Path,default=Path('.cache/reference/f16'))
    p.add_argument('--verify',action='store_true',help='Verify existing local import files against their recorded hashes')
    args=p.parse_args()
    if args.verify:
        for filename,expected in json.loads((args.output/'import-integrity.json').read_text()).items():
            if hashlib.sha256((args.output/filename).read_bytes()).hexdigest()!=expected:
                raise ValueError('Imported reference file changed: '+filename)
        print('Reference import integrity verified')
    else:
        archive=args.archive.read_bytes() if args.archive else urllib.request.urlopen(URL,timeout=60).read()
        import_archive(archive,args.output)
