# The random 32-byte key is a local/CI secret input, never a source file.
set(OFS_ASSET_KEY_FILE "" CACHE FILEPATH "File containing the protected content key (64 lowercase hex digits)")
set(OFS_PROTECTED_SU57_ROOT "" CACHE PATH "Root containing protected Su-57 assets for installation")
set(ofs_key_enabled false)
set(ofs_key_bytes "")
if(OFS_ASSET_KEY_FILE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${OFS_ASSET_KEY_FILE}")
  file(READ "${OFS_ASSET_KEY_FILE}" ofs_key_hex)
  string(STRIP "${ofs_key_hex}" ofs_key_hex)
  string(LENGTH "${ofs_key_hex}" ofs_key_length)
  if(NOT ofs_key_length EQUAL 64 OR NOT ofs_key_hex MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Content key must contain 64 lowercase hexadecimal digits")
  endif()
  set(ofs_key_enabled true)
  foreach(i RANGE 0 62 2)
    string(SUBSTRING "${ofs_key_hex}" ${i} 2 byte)
    string(APPEND ofs_key_bytes "0x${byte},")
  endforeach()
endif()
file(WRITE "${CMAKE_BINARY_DIR}/generated/ofs_asset_key.hpp"
  "#pragma once\ninline constexpr bool kOfsAssetKeyEnabled = ${ofs_key_enabled};\ninline constexpr unsigned char kOfsAssetKey[32] = {${ofs_key_bytes}};\n")
unset(ofs_key_hex)
unset(ofs_key_bytes)
if(OFS_PROTECTED_SU57_ROOT AND NOT OFS_ASSET_KEY_FILE)
  message(FATAL_ERROR "Protected Su-57 installation requires OFS_ASSET_KEY_FILE")
endif()
add_library(ofs_monocypher STATIC client/thirdparty/monocypher/monocypher.c)
target_include_directories(ofs_monocypher SYSTEM PUBLIC client/thirdparty/monocypher)
target_link_libraries(ofs_visual_core PRIVATE ofs_monocypher)
target_include_directories(ofs_visual_core PRIVATE "${CMAKE_BINARY_DIR}/generated")
add_executable(ofs_protected_asset_tool scripts/protected_asset_tool.cpp)
target_link_libraries(ofs_protected_asset_tool PRIVATE ofs_visual_core)
ofs_target_defaults(ofs_protected_asset_tool)

install(FILES "${CMAKE_SOURCE_DIR}/client/thirdparty/monocypher/LICENCE.md"
  DESTINATION licenses/monocypher)
