# vcpkg app-local deployment copies shared DLLs beside each executable.
# Merge only identical copies; different binaries remain a packaging error.
function(ofs_resolve_runtime_conflicts dependencies_variable prefix)
  set(resolved "${${dependencies_variable}}")
  foreach(filename IN LISTS ${prefix}_FILENAMES)
    set(copies "${${prefix}_${filename}}")
    list(GET copies 0 selected)
    file(SHA256 "${selected}" selected_hash)
    foreach(copy IN LISTS copies)
      file(SHA256 "${copy}" copy_hash)
      if(NOT copy_hash STREQUAL selected_hash)
        message(FATAL_ERROR "Conflicting runtime DLL contents for ${filename}: ${copies}")
      endif()
    endforeach()
    list(APPEND resolved "${selected}")
  endforeach()
  list(REMOVE_DUPLICATES resolved)
  set(${dependencies_variable} "${resolved}" PARENT_SCOPE)
endfunction()
